name = "Smoooooth"
license = "MIT"
licenselink = "https://github.com/luk3ya0/hugo-smoooooth/blob/master/LICENSE"
description = "Minimalist theme for reading"
homepage = "https://github.com/luke/hugo-smoooooth"
tags = ["blog"]
features = ["minimalist", "reading" ]
min_version = "0.41"

[author]
  name = "Luke Yao"
  homepage = "https://luk3ya0.github.io"

[original]
  author = "Zachary Wade Betz"
  homepage = "https://zwbetz.com/make-a-hugo-blog-from-scratch/"
  repo = "https://github.com/zwbetz-gh/make-a-hugo-blog-from-scratch"
